openapi: 3.0.0
info:
  title: Smart Tutor API
  version: 1.0.0

paths:
  /health:
    get:
      responses:
        '200':
          description: Health check successful

  /api:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                category:
                  type: string
      responses:
        '200':
          description: Successful API response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string  # This should be an actual JSON string, not a string representation
        '400':
          description: Invalid category
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
